function carregar() {
    var msg = window.document.getElementById('msg')
    var img = window.document.getElementById('imagem')
    var data = new Date()
    //var hora = data.getHours()
    var hora = 14

    
    msg.innerHTML = `Agora são ${hora} horas` 
    if (hora >= 0 && hora < 12) {
        //`Bom dia`
        img.src = 'manha..png'
        document.body.style.background = '#0d1203'
    } else if (hora >= 12 && hora < 18){
        // `Boa tarde`
        img.src = 'tarde.png'
        document.body.style.background = '#667079'
    } else {
        // `Boa noite`
        img.src = 'noite.png'
        document.body.style.background = '#795a42'
    } 
}